version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
